#!/bin/bash
# WS-3 handoff script — run from Josh's Mac to push and open the PR
# Generated by the WS-3 worker after the workspace bash environment
# couldn't perform the push (no GitHub credentials in the sandbox).
#
# The commit is already on the local branch feat/recall-quality at fd86411.

set -euo pipefail
cd /Users/Joshua/boardroom-platform

echo "==> Verifying commit is on local feat/recall-quality"
git log feat/recall-quality --oneline -1

echo "==> Pushing to origin"
git push -u origin feat/recall-quality

echo "==> Creating PR"
gh pr create \
  --base main \
  --head feat/recall-quality \
  --title "feat(recall): exp decay + 0.80 dedup + sourceWeight tiebreaker (WS-3)" \
  --body-file /Users/Joshua/boardroom-platform/.pr-body-ws3.md

echo "==> Done. PR URL printed above."
